.TH TERMIC 1 "August 2023" "Termic Manual"
.SH NAME
TermiC \- GCC powered interactive C/C++ terminal created with BASH
.SH SYNOPSIS
.TP 10
termic 
.TP 10
termic++ 
.TP 10
termic tcc 
.SH DESCRIPTION
TermiC is an interactive C/C++ terminal powered by GCC and written in BASH. 
All inputs given to TermiC are append to text file in /tmp directory. Then TermiC compiles that file and runs it. It simply takes the last line back if an output detected as all outputs should be seen once. TermiC nearly fully supports C and C++ as it basically use GCC and G++ compilers. All curly braces starts an inline prompt so nested functions, if/else statements, while/for loops, classes etc. can be used efficiently. I don't know if there is such a concept, but I hope it will be useful.
.SH COMMAND LINE COMMANDS
--help -h Shows the help menu 
--version -v Shows the version number

.SH PROMPT COMMANDS
.TP 10
\fBhelp\fR
Shows the help menu.

.TP 10
\fBabort\fR
Aborts inline prompt mode which is entered by curly bracket.

.TP 10
\fBshow\fR
Prints the last successfully compiled source file.

.TP 10
\fBshowtmp\fR
Prints the last compiled source file with deleted edits.

.TP 10
\fBsave\fR
Saves the source file to the working directory.

.TP 10
\fBsavebin\fR
Saves the binary file to the working directory.

.TP 10
\fBclear\fR
Deletes all declared functions, classes, etc. and resets the shell.

.TP 10
\fBexit\fR
Deletes created temp files and exits the program.

.SH AUTHORS
.TP 10
\fBYusuf Kagan Hanoglu\fR <hanoglu@yahoo.com>
.TP 10
\fBMax Schillinger\fR
